# Generated by Django 4.2.3 on 2023-07-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_itemcarrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
